### ISSUE TITLE
Update README to describe vs watchify/browserify

### ISSUE THREAD

**Issue by jprichardson** [jsdf/browserify-incremental#10]
How is this different than watchify / browserify combo? Maybe updating the README to explain the differences?

**Comment by justjake** [comment]
Watchify does not persist the cache across watchify restarts. browserify-incremental caches the compilation of each file (module) in your browserify bundle in a JSON blob, and restores this cache into memory the next time you start it. This (should) give you faster builds in build scripts, etc where you just want to compile/bundle once.

**Comment by stevenpetryk** [comment]
The README seems to contain this, recommending you close this @jsdf.
