### ISSUE TITLE
Ability to pass updated file to avoid mtime checks

### ISSUE THREAD

**Issue by alihammad-gist** [jsdf/browserify-incremental#16]
It would be nice to pass in the command line the file(s) which have updated to avoid any cache checks at all, for faster bundling.

```
browserifyinc build/main.js -o public/js/main.js --reload build/f1.js build/f2.js
```

**Comment by jsdf** [comment]
Perhaps, but it seems to me that caching with mtime invalidation is really the only benefit `browserify-incremental` provides. Your use case could be achieved by just using a thin wrapper around browserify which manages the `cache` opt which browserify takes in its constructor. If you known which files have changed, all you have to do is delete them from the `cache` opt object before bundling.

**Comment by alihammad-gist** [comment]
Thank you very much. I'd do as you suggested.
