### ISSUE TITLE
Crypto library does not work once cache is used

### ISSUE THREAD

**Issue by stevenpetryk** [jsdf/browserify-incremental#19]
Can be reproduced using [this test repo](https://github.com/stevenpetryk/browserify-incremental-crypto) I made. The error is `Uncaught TypeError: Cannot read property 'version' of undefined`, which is being thrown by the `elliptic.js` module of Browserify's `crypto` implementation. This only happens after the cache begins being used, which is incidentally after running browserify-incremental three times (see #8).

It's worth noting that the Watchify library has encountered the same problem (substack/watchify#130, indutny/elliptic#30).

**Comment by stevenpetryk** [comment]
The specific commit where the issue was fixed in watchify is Pleochism/watchify@e9fe543a8ff45b125273159dbd1477f2b9cc4759.

**Comment by jreading** [comment]
Same issue.

**Comment by AgentME** [comment]
That linked commit was never merged into watchify. This is where it got fixed in watchify: https://github.com/substack/watchify/pull/160. It looks like browserify-incremental works like how watchify worked before that change.

**Comment by jsdf** [comment]
This should be fixed in [v3.1.0](https://github.com/jsdf/browserify-incremental/releases/tag/v3.1.0)
