### ISSUE TITLE
fullpaths option

### ISSUE THREAD

**Issue by sprat** [jsdf/browserify-incremental#25]
I would like to generate bundles without the fullPaths option, because I use browserifyinc to generate deployment builds and these paths conflict with other developers' builds. However, it seems that this option is a requirement for browserify-incremental in order to cache the files. Is there a way to avoid that problem?

It seems that watchify suffered from the same problem but it has been solved: see https://github.com/substack/watchify/issues/78

**Comment by jsdf** [comment]
If it works for watchify it should work for browserify-incremental. Alternatively you could use the intreq plugin for browserify to rewrite the module ids to strip the paths out of the final bundle.

**Comment by sprat** [comment]
No, due to https://github.com/jsdf/browserify-cache-api/blob/master/lib/BrowserifyCache.js#L25
and https://github.com/jsdf/browserify-cache-api/blob/master/lib/BrowserifyCache.js#L47. Maybe it can work without these lines?

As for the intreq suggestion, I didn't try it, but tried bundle-collapser instead and it does not work because the fullPaths option is applied *after* the bundle-collapser plugin. I will see if intreq has the same problem.

**Comment by jsdf** [comment]
fullPaths option is no longer required in in [v3.1.0](https://github.com/jsdf/browserify-incremental/releases/tag/v3.1.0)
