### ISSUE TITLE
allow --verbose mode without specifying an outfile

### ISSUE THREAD

**Issue by ianthehenry** [jsdf/browserify-incremental#4]
I'm not sure why this restriction is in place, since the debug information is being correctly written to stderr.

It's a simple change, but apparently I can't create a PR for it as `master` doesn't include any recent tag-only releases.

https://github.com/ianthehenry/browserify-incremental/commit/3eff0c4460522d73ea6b0a1c529677ff632712d6

**Comment by jsdf** [comment]
Sorry about that! I've just pushed master so you can make this into a PR against master and I'll merge it

**Comment by ianthehenry** [comment]
It is done, thanks!

**Comment by ianthehenry** [comment]
I guess *technically* the issue is still open.
